#!/usr/bin/env python
"""Prep step for the two-sided front analysis.

Confirms that the chosen LLC pixel sub-region sits in the
Brazil-Malvinas region and plots the relative vorticity field over
that sub-region.

Generated by JXP and Claude
"""

import os

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

import xarray as xr
import gsw

from fronts.llc.coords import ij_to_latlon

# Pixel ranges for the Brazil-Malvinas test region (i==x, j==y).
# NOTE: the ranges originally stated in the prompt, i=[250,450] and
# j=[500,700], actually fall on the Antarctic/South-Pole region of the
# LLC4320 rectangular grid (center lat=-86.9, lon=-40.8) where the
# vorticity field is entirely NaN.  The ranges below were derived with
# fronts.llc.coords.latlon_to_ij from the Brazil-Malvinas confluence
# (~ -39 lat, -53 lon) and span lat [-40.5, -37.5], lon [-55.1, -50.9].
I_RANGE = (16459, 16659)
J_RANGE = (5611, 5811)

# Path to the relative vorticity snapshot used for development
VORT_FILE = os.path.join(
    os.getenv('OS_OGCM'), 'LLC', 'Fronts', 'V4', '20121109_120000',
    'LLC4320_2012-11-09T12_00_00_relative_vorticity_sfc_V4.nc')

# Path to the global labeled-fronts array (same directory as VORT_FILE)
FRONT_FILE = os.path.join(
    os.path.dirname(VORT_FILE),
    'labeled_fronts_global_20121109T12_00_00_V4.npy')

# Where figures and outputs for this prep step are written
OUT_DIR = os.path.dirname(os.path.abspath(__file__))


def confirm_center(i_range=I_RANGE, j_range=J_RANGE):
    """Report the (lat, lon) of the sub-region center and corners.

    Parameters
    ----------
    i_range : tuple of int
        ``(i_min, i_max)`` column (x) pixel range.
    j_range : tuple of int
        ``(j_min, j_max)`` row (y) pixel range.

    Returns
    -------
    dict
        Keys ``'center'`` and ``'corners'`` mapping to ``(lat, lon)``
        tuples (degrees, lon wrapped to [-180, 180]).

    Generated by JXP and Claude
    """
    # Center pixel of the requested range
    i_c = (i_range[0] + i_range[1]) // 2
    j_c = (j_range[0] + j_range[1]) // 2

    # Convert the center pixel to (lat, lon)
    lat_c, lon_c = ij_to_latlon(i_c, j_c)

    # Convert each of the four corners as a sanity check on extent
    corners = {}
    for i in i_range:
        for j in j_range:
            corners[(i, j)] = ij_to_latlon(i, j)

    # Print a human-readable summary
    print(f'Center pixel i={i_c} j={j_c} -> '
          f'lat={lat_c:.4f} lon={lon_c:.4f}')
    for (i, j), (lat, lon) in corners.items():
        print(f'  corner i={i} j={j} -> lat={lat:.4f} lon={lon:.4f}')

    return {'center': (lat_c, lon_c), 'corners': corners}


def plot_vorticity(i_range=I_RANGE, j_range=J_RANGE, vort_file=VORT_FILE):
    """Plot the relative vorticity field over the test sub-region.

    Parameters
    ----------
    i_range : tuple of int
        ``(i_min, i_max)`` column (x) pixel range.
    j_range : tuple of int
        ``(j_min, j_max)`` row (y) pixel range.
    vort_file : str
        Path to the relative vorticity NetCDF snapshot.

    Returns
    -------
    str
        Path to the saved figure (PNG).

    Generated by JXP and Claude
    """
    # Open lazily; only the sub-region is loaded into memory below
    ds = xr.open_dataset(vort_file)

    # Slice the sub-region (x==i, y==j); +1 to include the upper bound
    sub = ds['relative_vorticity_sfc'].isel(
        x=slice(i_range[0], i_range[1] + 1),
        y=slice(j_range[0], j_range[1] + 1)).load()

    # Symmetric color limits so positive/negative vorticity are balanced
    vmax = float(np.nanpercentile(np.abs(sub.values), 99))

    # Lat/lon of the sub-region center for the title
    lat_c, lon_c = ij_to_latlon(
        (i_range[0] + i_range[1]) // 2,
        (j_range[0] + j_range[1]) // 2)

    # Render the field
    fig, ax = plt.subplots(figsize=(7, 7))
    im = ax.pcolormesh(sub.x, sub.y, sub.values,
                       cmap='RdBu_r', vmin=-vmax, vmax=vmax,
                       shading='auto')
    ax.set_xlabel('i (x pixel)')
    ax.set_ylabel('j (y pixel)')
    ax.set_aspect('equal')
    ax.set_title('Relative vorticity (sfc) - Brazil-Malvinas\n'
                 f'center lat={lat_c:.2f} lon={lon_c:.2f}')
    cbar = fig.colorbar(im, ax=ax, shrink=0.8)
    cbar.set_label('relative vorticity (s$^{-1}$)')

    # Save next to this script
    out_file = os.path.join(OUT_DIR, 'relative_vorticity_test_region.png')
    fig.savefig(out_file, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f'Wrote {out_file}')

    return out_file


def plot_normalized_vorticity_with_fronts(
        i_range=I_RANGE, j_range=J_RANGE, vort_file=VORT_FILE,
        front_file=FRONT_FILE):
    """Plot vorticity / f (Rossby number) with fronts overplotted.

    The relative vorticity is normalized by the Coriolis parameter ``f``
    evaluated at the sub-region center latitude (a single approximate
    value is adequate over this small box).  Labeled fronts are
    overplotted as semi-transparent yellow.

    Parameters
    ----------
    i_range : tuple of int
        ``(i_min, i_max)`` column (x) pixel range.
    j_range : tuple of int
        ``(j_min, j_max)`` row (y) pixel range.
    vort_file : str
        Path to the relative vorticity NetCDF snapshot.
    front_file : str
        Path to the global labeled-fronts ``.npy`` array (int labels;
        0 == no front, >0 == front-segment label).

    Returns
    -------
    str
        Path to the saved figure (PNG).

    Generated by JXP and Claude
    """
    # Load the vorticity sub-region (x==i, y==j); +1 to include upper bound
    ds = xr.open_dataset(vort_file)
    sub = ds['relative_vorticity_sfc'].isel(
        x=slice(i_range[0], i_range[1] + 1),
        y=slice(j_range[0], j_range[1] + 1)).load()

    # Memory-map the global fronts array and slice the same window so we
    # never pull the full ~1.8 GB grid into memory
    fronts_global = np.load(front_file, mmap_mode='r')
    fronts = np.asarray(
        fronts_global[j_range[0]:j_range[1] + 1,
                      i_range[0]:i_range[1] + 1])

    # Coriolis parameter at the center latitude; f = 2*Omega*sin(lat).
    # gsw.f returns the signed value (negative in the S. hemisphere), so
    # vorticity/f is the Rossby number with positive == cyclonic.
    lat_c, lon_c = ij_to_latlon(
        (i_range[0] + i_range[1]) // 2,
        (j_range[0] + j_range[1]) // 2)
    f_cor = gsw.f(lat_c)

    # Normalized vorticity (Rossby number)
    ro = sub.values / f_cor

    # Symmetric color limits about zero
    vmax = float(np.nanpercentile(np.abs(ro), 99))

    fig, ax = plt.subplots(figsize=(7, 7))
    im = ax.pcolormesh(sub.x, sub.y, ro,
                       cmap='RdBu_r', vmin=-vmax, vmax=vmax,
                       shading='auto')

    # Overplot fronts: mask non-front pixels to NaN and paint the rest
    # solid yellow at low alpha so the vorticity field shows through
    front_layer = np.where(fronts > 0, 1.0, np.nan)
    ax.pcolormesh(sub.x, sub.y, front_layer,
                  cmap=ListedColormap(['yellow']),
                  alpha=0.4, shading='auto')

    ax.set_xlabel('i (x pixel)')
    ax.set_ylabel('j (y pixel)')
    ax.set_aspect('equal')
    ax.set_title('Vorticity / f  with fronts (yellow) - Brazil-Malvinas\n'
                 f'center lat={lat_c:.2f} lon={lon_c:.2f}  '
                 f'f={f_cor:.2e} s$^{{-1}}$')
    cbar = fig.colorbar(im, ax=ax, shrink=0.8)
    cbar.set_label(r'Rossby number  $\zeta / f$')

    out_file = os.path.join(
        OUT_DIR, 'rossby_with_fronts_test_region.png')
    fig.savefig(out_file, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f'Wrote {out_file}  (f={f_cor:.3e} s^-1 at lat={lat_c:.2f})')

    return out_file


def main():
    """Run the prep step: confirm center, plot vorticity, then plot the
    Coriolis-normalized vorticity with fronts overplotted.

    Generated by JXP and Claude
    """
    confirm_center()
    plot_vorticity()
    plot_normalized_vorticity_with_fronts()


if __name__ == '__main__':
    main()
