#!/usr/bin/env python
"""Two-sided front property measurement (development module).

Measures a property (the Rossby number) separately on the two flanking
sides of each labeled front -- the lighter vs heavier (potential
density) side -- excluding the front pixels themselves.  Implements the
plan in prompts/fronts_two_sided.md.

This lives in dev/ for now but is intended to migrate into
fronts/properties/colocation.py.

Generated by JXP and Claude
"""

import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

from scipy import ndimage
import gsw
import xarray as xr

from fronts.llc.coords import load_coords
from prep_test_region import (
    I_RANGE, J_RANGE, VORT_FILE, FRONT_FILE, OUT_DIR)

# Property / density source files (same snapshot dir as VORT_FILE)
_SNAP = os.path.dirname(VORT_FILE)
_PRE = 'LLC4320_2012-11-09T12_00_00_'
RO_FILE = os.path.join(_SNAP, _PRE + 'Ro_sfc_V4.nc')
THETA_FILE = os.path.join(_SNAP, _PRE + 'Theta_sfc_V4.nc')
SALT_FILE = os.path.join(_SNAP, _PRE + 'Salt_sfc_V4.nc')

# Fixed band width (pixels) per the Clarifications
R_DEFAULT = 3


def potential_density(theta, salt, lat, lon):
    """Potential density anomaly sigma0 from surface T and S.

    Parameters
    ----------
    theta : np.ndarray
        Potential temperature (deg C) at the surface.
    salt : np.ndarray
        Practical salinity (PSU) at the surface.
    lat, lon : np.ndarray
        Latitude / longitude (deg) on the same grid as theta/salt.

    Returns
    -------
    np.ndarray
        Potential density anomaly sigma0 (kg m^-3), same shape as input.

    Generated by JXP and Claude
    """
    # Surface pressure ~ 0 dbar; gsw converts practical -> absolute
    # salinity and potential -> conservative temperature first
    SA = gsw.SA_from_SP(salt, 0.0, lon, lat)
    CT = gsw.CT_from_pt(SA, theta)
    return gsw.sigma0(SA, CT)


def load_region(i_range=I_RANGE, j_range=J_RANGE):
    """Load fronts, Rossby number and sigma0 over the test box.

    Parameters
    ----------
    i_range, j_range : tuple of int
        Inclusive ``(min, max)`` pixel ranges in x (i) and y (j).

    Returns
    -------
    dict
        ``fronts``, ``ro``, ``sigma0``, ``theta``, ``salt``, ``lat``,
        ``lon`` arrays plus the ``i_range``/``j_range`` used.

    Generated by JXP and Claude
    """
    # +1 to make the upper bound inclusive
    isl = slice(i_range[0], i_range[1] + 1)
    jsl = slice(j_range[0], j_range[1] + 1)

    # Labeled fronts: memory-map then slice the window
    fronts = np.asarray(np.load(FRONT_FILE, mmap_mode='r')[jsl, isl])

    # Rossby number (precomputed) and the T/S fields for density
    ro = xr.open_dataset(RO_FILE)['Ro_sfc'].isel(x=isl, y=jsl).values
    theta = xr.open_dataset(THETA_FILE)['Theta_sfc'].isel(
        x=isl, y=jsl).values
    salt = xr.open_dataset(SALT_FILE)['Salt_sfc'].isel(x=isl, y=jsl).values

    # Coordinates (aligned element-wise with the data grid)
    coords = load_coords(verbose=False)
    lat = coords.lat.values[jsl, isl]
    lon = ((coords.lon.values[jsl, isl] + 180) % 360) - 180

    sigma0 = potential_density(theta, salt, lat, lon)

    return dict(fronts=fronts, ro=ro, sigma0=sigma0, theta=theta,
                salt=salt, lat=lat, lon=lon,
                i_range=i_range, j_range=j_range)


def assign_two_sides(labeled_fronts, R=R_DEFAULT, smooth_sigma=1.5):
    """Split the dilation band of each front into its two flanks.

    Uses a single Euclidean distance transform: every background pixel
    learns its distance to the front and the location of its nearest
    front pixel.  A signed side is then assigned from the local front
    normal (gradient of a blurred front mask).

    Parameters
    ----------
    labeled_fronts : np.ndarray
        Integer label array (0 == background, >0 == front segment).
    R : int
        Band half-width in pixels (each side extends R pixels out).
    smooth_sigma : float
        Gaussian sigma used to estimate the local front normal.

    Returns
    -------
    dict
        ``band`` (bool, dist in (0, R]), ``side`` (+1/-1/0 per pixel),
        ``front_of`` (nearest front label per pixel), ``dist``.

    Generated by JXP and Claude
    """
    M = labeled_fronts > 0

    # One transform: distance to front + index of nearest front pixel
    dist, (qy, qx) = ndimage.distance_transform_edt(
        ~M, return_indices=True)

    # Measurement band; dist>0 drops the front pixels themselves
    band = (dist > 0) & (dist <= R)

    # Local front normal = gradient of a blurred front mask
    Ms = ndimage.gaussian_filter(M.astype(float), smooth_sigma)
    gy, gx = np.gradient(Ms)

    # Pixel coordinate grids and offset from nearest front pixel
    Y, X = np.indices(labeled_fronts.shape)
    vy = Y - qy
    vx = X - qx

    # Normal sampled at each pixel's nearest front pixel
    nqy = gy[qy, qx]
    nqx = gx[qy, qx]

    # Signed flank: sign of (offset . normal)
    side = np.sign(vy * nqy + vx * nqx)

    # Label of the front each band pixel is assigned to
    front_of = labeled_fronts[qy, qx]

    return dict(band=band, side=side, front_of=front_of, dist=dist)


def _counts_per_label(label_arr, flabels):
    """Pixel count per front label in a side-label array.

    Generated by JXP and Claude
    """
    flat = label_arr.ravel()
    bc = np.bincount(flat, minlength=int(flabels.max()) + 1)
    return bc[flabels]


def two_sided_colocate(labeled_fronts, ro, sigma0, R=R_DEFAULT):
    """Measure the Rossby number on each side of every front.

    Sides are split geometrically (see :func:`assign_two_sides`) then
    named light/heavy per front by their mean potential density.

    Parameters
    ----------
    labeled_fronts : np.ndarray
        Integer label array (0 == background).
    ro : np.ndarray
        Rossby number field, same shape as ``labeled_fronts``.
    sigma0 : np.ndarray
        Potential density field used to name the sides.
    R : int
        Band half-width in pixels.

    Returns
    -------
    pd.DataFrame
        Wide format, one row per front: ``flabel``,
        ``npix_light``/``npix_heavy``,
        ``Ro_{mean,median}_{light,heavy}``,
        ``Ro_{mean,median}_delta`` (= heavy - light),
        ``sigma0_mean_{light,heavy}``.

    Generated by JXP and Claude
    """
    info = assign_two_sides(labeled_fronts, R=R)
    band, side, front_of = info['band'], info['side'], info['front_of']

    # Valid band pixels with a defined flank
    valid = band & (side != 0)

    # Geometric-side label arrays (+1 -> "pos", -1 -> "neg")
    labels_pos = np.where(valid & (side > 0), front_of, 0)
    labels_neg = np.where(valid & (side < 0), front_of, 0)

    flabels = np.unique(labeled_fronts)
    flabels = flabels[flabels > 0]
    if len(flabels) == 0:
        return pd.DataFrame()

    # Per-front, per-side reducer (nan-aware)
    def stat(arr, labels, fn):
        return ndimage.labeled_comprehension(
            arr.astype(float), labels, flabels, fn, np.float64, np.nan)

    # Geometric-side statistics
    ro_mean_pos = stat(ro, labels_pos, np.nanmean)
    ro_mean_neg = stat(ro, labels_neg, np.nanmean)
    ro_med_pos = stat(ro, labels_pos, np.nanmedian)
    ro_med_neg = stat(ro, labels_neg, np.nanmedian)
    sig_pos = stat(sigma0, labels_pos, np.nanmean)
    sig_neg = stat(sigma0, labels_neg, np.nanmean)
    n_pos = _counts_per_label(labels_pos, flabels)
    n_neg = _counts_per_label(labels_neg, flabels)

    # Name sides by density: the higher-sigma0 side is "heavy".  NaNs
    # (a missing side) compare False, so a present side wins.
    heavy_is_pos = np.nan_to_num(sig_pos, nan=-np.inf) >= \
        np.nan_to_num(sig_neg, nan=-np.inf)

    def pick(pos, neg):
        # Return (light, heavy) arrays per front
        heavy = np.where(heavy_is_pos, pos, neg)
        light = np.where(heavy_is_pos, neg, pos)
        return light, heavy

    npix_l, npix_h = pick(n_pos, n_neg)
    ro_mean_l, ro_mean_h = pick(ro_mean_pos, ro_mean_neg)
    ro_med_l, ro_med_h = pick(ro_med_pos, ro_med_neg)
    sig_l, sig_h = pick(sig_pos, sig_neg)

    return pd.DataFrame({
        'flabel': flabels,
        'npix_light': npix_l,
        'npix_heavy': npix_h,
        'Ro_mean_light': ro_mean_l,
        'Ro_mean_heavy': ro_mean_h,
        'Ro_mean_delta': ro_mean_h - ro_mean_l,
        'Ro_median_light': ro_med_l,
        'Ro_median_heavy': ro_med_h,
        'Ro_median_delta': ro_med_h - ro_med_l,
        'sigma0_mean_light': sig_l,
        'sigma0_mean_heavy': sig_h,
    })


def plot_single_front(flabel=44131, R=R_DEFAULT, i_range=I_RANGE,
                      j_range=J_RANGE, pad=12):
    """Plot one front, its two density-named sides, and side stats.

    Parameters
    ----------
    flabel : int
        Front label to visualize.
    R : int
        Band half-width in pixels.
    i_range, j_range : tuple of int
        Test-box pixel ranges to load.
    pad : int
        Extra pixels around the front bounding box for the zoom.

    Returns
    -------
    tuple
        ``(out_file, df)`` -- saved figure path and the one-row
        two-sided DataFrame for this front.

    Generated by JXP and Claude
    """
    reg = load_region(i_range, j_range)
    i0, j0 = i_range[0], j_range[0]

    # Isolate the single front in its own label array
    single = np.where(reg['fronts'] == flabel, flabel, 0)
    if not np.any(single):
        raise ValueError(f'Front {flabel} not in the test box')

    # Two-sided measurement for this front (one-row DataFrame)
    df = two_sided_colocate(single, reg['ro'], reg['sigma0'], R=R)

    # Recompute the per-pixel side masks for plotting
    info = assign_two_sides(single, R=R)
    side, band = info['side'], info['band']
    valid = band & (side != 0) & (info['front_of'] == flabel)

    # Which geometric side is heavy (higher mean sigma0)?
    sig_pos = np.nanmean(reg['sigma0'][valid & (side > 0)])
    sig_neg = np.nanmean(reg['sigma0'][valid & (side < 0)])
    heavy_is_pos = sig_pos >= sig_neg
    heavy_mask = valid & ((side > 0) == heavy_is_pos)
    light_mask = valid & ((side > 0) != heavy_is_pos)
    front_mask = single > 0

    # Zoom window around the front (local indices -> global pixels)
    ys, xs = np.where(front_mask)
    y_lo, y_hi = ys.min() - pad, ys.max() + pad
    x_lo, x_hi = xs.min() - pad, xs.max() + pad

    # Global pixel coordinate vectors for pcolormesh
    nx = reg['ro'].shape[1]
    ny = reg['ro'].shape[0]
    xco = i0 + np.arange(nx)
    yco = j0 + np.arange(ny)

    fig, ax = plt.subplots(figsize=(8, 7))

    # Background: Rossby number, symmetric color scale
    vmax = float(np.nanpercentile(np.abs(reg['ro']), 99))
    im = ax.pcolormesh(xco, yco, reg['ro'], cmap='RdBu_r',
                       vmin=-vmax, vmax=vmax, shading='auto')

    # Overlay the two sides and the front line
    ax.pcolormesh(xco, yco, np.where(light_mask, 1.0, np.nan),
                  cmap=ListedColormap(['cyan']), alpha=0.55,
                  shading='auto')
    ax.pcolormesh(xco, yco, np.where(heavy_mask, 1.0, np.nan),
                  cmap=ListedColormap(['magenta']), alpha=0.55,
                  shading='auto')
    ax.pcolormesh(xco, yco, np.where(front_mask, 1.0, np.nan),
                  cmap=ListedColormap(['black']), shading='auto')

    ax.set_xlim(i0 + x_lo, i0 + x_hi)
    ax.set_ylim(j0 + y_lo, j0 + y_hi)
    ax.set_aspect('equal')
    ax.set_xlabel('i (x pixel)')
    ax.set_ylabel('j (y pixel)')

    # Annotate per-side stats from the DataFrame
    row = df.iloc[0]
    txt = (f'front {flabel}  (R={R})\n'
           f'light: Ro_mean={row.Ro_mean_light:.3f} '
           f'sigma0={row.sigma0_mean_light:.3f} '
           f'n={int(row.npix_light)}\n'
           f'heavy: Ro_mean={row.Ro_mean_heavy:.3f} '
           f'sigma0={row.sigma0_mean_heavy:.3f} '
           f'n={int(row.npix_heavy)}\n'
           f'delta Ro_mean (heavy-light)={row.Ro_mean_delta:.3f}')
    ax.set_title('Two-sided front: cyan=light, magenta=heavy, '
                 'black=front')
    ax.text(0.02, 0.02, txt, transform=ax.transAxes, fontsize=8,
            va='bottom', ha='left',
            bbox=dict(boxstyle='round', fc='white', alpha=0.8))

    cbar = fig.colorbar(im, ax=ax, shrink=0.8)
    cbar.set_label('Rossby number Ro')

    out_file = os.path.join(OUT_DIR, f'two_sided_front_{flabel}.png')
    fig.savefig(out_file, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f'Wrote {out_file}')

    return out_file, df


def main():
    """Run the two-sided measurement on front 44131 and plot it.

    Generated by JXP and Claude
    """
    #out_file, df = plot_single_front(44131)
    out_file, df = plot_single_front(43707)
    # Print the one-row result with full precision
    with pd.option_context('display.width', 120,
                           'display.max_columns', None):
        print(df.to_string(index=False))


if __name__ == '__main__':
    main()
